#!/bin/bash

for i in `seq 1 5`
do
  cp travis_1.yml .travis.yml
  git add .
  git commit -m "Slow experiment: Option 1"
  git push

  sleep 300

  cp travis_2.yml .travis.yml
  git add .
  git commit -m "Slow experiment: Option 2"
  git push

  sleep 300

done
